# Generated by Django 3.2.4 on 2021-07-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('catid', models.IntegerField()),
                ('subcatid', models.IntegerField()),
                ('pdescription', models.CharField(max_length=100)),
                ('bprice', models.IntegerField()),
                ('piconnm', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
